#!/bin/bash

# Update wallpaper and colors
sh $HOME/Dotfiles/scripts/theme_changer.sh

#start input manager
sxhkd -c $HOME/.config/sxhkd/sxhkdrc &

#start bar
sh $HOME/.config/bar/launchbar.sh

# set berry color
sh $HOME/.cache/wal/berrycolor

# launch notification
sh $HOME/Scripts/startdunst &

# Set decoration geometry
berryc border_width         7
berryc inner_border_width   0
berryc top_gap              0
berryc title_height         25

# Other options
berryc smart_place "true"
berryc draw_text   "false"
berryc edge_lock   "true"
berryc set_font    "Cascadia Code"

# Wifi-tray
nm-applet &

# Filter
redshift &

# Music !
mpd &

# lighter than compton for sure
xcompmgr -c -r 10 -o .4 -t -5 -l -5 -C &