#!/bin/bash

WALL="$(ls ~/Dotfiles/wallpaper | shuf -n 1)"
WALLPATH="/home/moussa/Dotfiles/wallpaper/$WALL"

if [ "$1" != "-l" ]
    then
        wal -i $WALLPATH -q
    else
        wal -l -i $WALLPATH -q
fi

kill "$(pgrep -f walblurbg)"
while pgrep -f walblurbg >/dev/null; do sleep 1; done

sh ~/Dotfiles/walblurbg &
sh ~/Dotfiles/bar/launchbar.sh
sh ~/.cache/wal/berrycolor
