#!/bin/bash

WALL="$(ls ~/Dotfiles/wallpaper | shuf -n 1)"
WALLPATH="/home/moussa/Dotfiles/wallpaper/$WALL"

if [ "$1" != "-l" ]
    then
        wal -i $WALLPATH -q
    else
        wal -l -i $WALLPATH -q
fi

# kill previous instance
to_kill="$(pgrep -f walblurbg)"
if [ ! -z "$to_kill" ]
    then
        kill $to_kill
    else
        echo "No walblur bg instance detected"
fi

sh ~/.cache/wal/berrycolor
sh ~/Dotfiles/berry/startdunst
sh ~/Dotfiles/bar/launchbar.sh
sh ~/Dotfiles/walblurbg &
notify-send -i "$WALLPATH" "Updated theme !"
