#!/bin/bash
killall -q dunst

# Strat notif deamon
source ~/.cache/wal/colors.sh
dunst -frame_width 0 -lb "${color0}" -nb "${color0}" -cb "${color0}" -lf "${color7}" -bf "${color7}" -cf "${color7}" -nf "${color7}" &