#!/bin/bash

# Set decoration colors
berryc focus_color          {background.strip}
berryc unfocus_color        {background.strip}
berryc inner_focus_color    {color3.strip}
berryc inner_unfocus_color  {color4.strip}
# berryc text_focus_color    ffffff
# berryc text_unfocus_color  eeeeee
