#!/bin/bash

# Set decoration colors
berryc focus_color          {color4.strip}
berryc unfocus_color        {color5.strip}
berryc inner_focus_color    {color3.strip}
berryc inner_unfocus_color  {color2.strip}
berryc text_focus_color     {background.strip}
berryc text_unfocus_color   {foreground.strip}