#!/bin/bash

# Set decoration colors
berryc focus_color          {color5.strip}
berryc unfocus_color        {color8.strip}
berryc inner_focus_color    {color4.strip}
berryc inner_unfocus_color  {color4.strip}
berryc text_focus_color     {foreground.strip}
berryc text_unfocus_color   {foreground.strip}